GET https://fullstack-open-part3-restless-dust-811.fly.dev/info
# GET http://localhost:3002/info

###
# GET http://localhost:3002/api/persons/
GET https://fullstack-open-part3-restless-dust-811.fly.dev/api/persons

###
GET https://fullstack-open-part3-restless-dust-811.fly.dev/api/persons/67b0e084087101f95de559dd
# GET http://localhost:3002/api/persons/67b0e084087101f95de559dd

###
DELETE https://fullstack-open-part3-restless-dust-811.fly.dev/api/persons/2

###
# POST http://localhost:3002/api/persons
POST https://fullstack-open-part3-restless-dust-811.fly.dev/api/persons
Content-Type: application/json

{
    "name": "araju",
    "number": "89898-4312"
}
