GET https://fullstack-open-part3-restless-dust-811.fly.dev/info

###
GET https://fullstack-open-part3-restless-dust-811.fly.dev/api/persons

###
GET https://fullstack-open-part3-restless-dust-811.fly.dev/api/persons/5

###
DELETE https://fullstack-open-part3-restless-dust-811.fly.dev/api/persons/2

###
POST https://fullstack-open-part3-restless-dust-811.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Prateek Kumar Jha",
    "number": "9754611342"
}
